Da Sie sich auch zu dem Thema Corona und Impfung geäußert haben, würde ich Ihnen gerne folgende Links übersenden.

Aushebelung unserer freiheitlichen Grundordnung wegen einem Virus?
Aushebelung unserer Grundrechte, der freiheitlichen Grundordnung und Abschaffung der föderalen Struktur wegen einem Virus?
•	Dr. Pieter Schleiter ist Richter und äußert sich zur aktuellen Situation unseres Rechtsstaats - vom 10.03.2021
https://odysee.com/@Deutsche-Mitte:7/202110032205:6

•	Prof. Uwe Volkmann (Rechtswissenschaftler) zur Abschaffung unserer Demokratie - vom 08.09.2021
https://odysee.com/@Deutsche-Mitte:7/202104222015:f
•	Der Rechtsstaat in der Krise. Hintergründe mit Rechtswissenschaftler Prof. Martin Schwab - vom 04.10.2020
https://odysee.com/@Deutsche-Mitte:7/202108182011:2
•	Über 3.000 Ärzte und Wissenschaftler unterzeichnen eine Erklärung, in der sie COVID-Entscheidungsträger der „Verbrechen gegen die Menschlichkeit“ beschuldigen. Vom 02.10.2021
https://odysee.com/@Impfsch%C3%A4den:a/202111302215:b
https://www.internationalcovidsummit.com

•	Der Staatsrechtler Professor Dr. Dietrich Murswiek bestätigt mit seinem Rechtsgutachten die Verfassungswidrigkeit des indirekten COVID-19-Impfzwangs - vom 04.10.2021

Zusammenfassung
https://impfentscheidung.online/wp-content/uploads/2021/10/Kurzzusammenfassung-Gutachten.pdf
https://tinyurl.com/nnandjsz

Gesamtes Rechtsgutachten
https://impfentscheidung.online/wp-content/uploads/2021/10/Gutachten-Die-Verfassungswidrigkeit-des-indirekten-Corona-Impfzwangs.pdf
https://tinyurl.com/j6y3djuv
Interview
https://odysee.com/@Deutsche-Mitte:7/202110092114:d
https://tinyurl.com/3zk9kbwc

•	Der Verwaltungsgerichtshof Bayern hat die Ausgangsperre von März 2021 (BayMBl. 2020 Nr. 162) für unwirksam und damit rechtswidrig erklärt.
VGH München, Beschluss v. 04.10.2021 – 20 N 20.767
https://www.gesetze-bayern.de/Content/Document/Y-300-Z-BECKRS-B-2021-N-29086


PCR-Test als einziger Nachweis einer i.d.R. symptomlosen Erkundung?
•	Urteil des VWG in Wien mit Aussage zum PCR-Test Wien… Ab Seite 8 letzter Absatz…
http://verwaltungsgericht.wien.gv.at/Content.Node/rechtsprechung/103-048-3227-2021.pdf
•	Kary Mullis, Erfinder der PCR Testmethode und Nobelpreisträger informiert
https://www.youtube.com/watch?v=LvNbvD0YI54

•	Ärzteblatt v. 12.06.2020 zur Belastbarkeit des PCR-Test des Herren Drosten
https://www.aerzteblatt.de/archiv/214370/PCR-Tests-auf-SARS-CoV-2-Ergebnisse-richtig-interpretieren
https://tinyurl.com/h7w2rep6
•	Urteil – das AG Weimar hat sich umfassend durch Sachverständige beraten lassen und auf 178 Seiten zu Corona und den Maßnahmen geäußert und alles als rechtswidrig und unsinnig erkannt.
https://openjur.de/u/2334639.print
•	Das Familiengericht des AG Weilheim kommt in gleichgelagerter Sache zu einem ähnlichem Ergebnis - Beschl. v. 3.04.2021, Az. 2 F 192/21
http://dschneble.tssd.de/blog/wp-content/uploads/2021/04/AG-Weilheim.pdf
•	Universität Duisburg und Essen weisen im renommierten Journal of Infection darauf hin, dass der PCR-Test nicht aussagefähig ist. Bis zu 78 % der Tests sind falsch positiv.
https://www.uni-due.de/2021-06-18-studie-aussagekraft-von-pcr-tests
https://tinyurl.com/refe42eh

Beitrag im Journal of Infection
https://www.journalofinfection.com/article/S0163-4453(21)00265-6/fulltext
https://tinyurl.com/9er6dxhv

Die Situation der Intensivstationen
•	Bezüglich der Intensivbetten konnte man auf der Webseite des DIVI 2020 sehr gut nachlesen und erkennen, dass die mediale Panikmache von den Intensivbetten nicht stimmt. Als sich das langsam aber sicher herum gesprochen hat, wurden kurzer Hand vorsätzlich und künstlich Anreize geschaffen damit Krankenhäuser anders agieren.

Hier wird sehr genau erklärt wie das zusammenhängt und man eine Panikpandemie steuert - vom 23.04.2021
https://www.bitchute.com/video/oqUtg6oPJBU/
•	Die aufgeflogene aber in den Medien etwas unterschlagene Lüge mit den Intensivbetten - vom 22.05.2021
https://www.bitchute.com/video/QzLIUOl9Hq2j
•	Nur zwei Prozent der Patienten waren 2020 an oder mit Corona in den Kliniken - Regierung schweigt zu der Skandalzahl - vom 20.09.2021

Das belegt ein Gutachten des Leibniz-Instituts für Wirtschaftsforschung im Auftrag des Bundesgesundheitsministeriums.

https://reitschuster.de/post/nur-zwei-prozent-corona-patienten-2020-in-den-kliniken-regierung-schweigt-zu-skandal-zahl/
https://tinyurl.com/58t3ev43
Das Gutachten vom 30.04.2021 als PDF
https://www.bundesgesundheitsministerium.de/fileadmin/Dateien/3_Downloads/C/Coronavirus/Analyse_Leistungen_Ausgleichszahlungen_2020_Corona-Krise.pdf
https://tinyurl.com/mrxnek8m


Die Impfstoffe
•	Immuntoxikologe Prof. Stefan Hockertz zum Gebrauch von Masken
https://www.bitchute.com/video/K3BjgsZT4Iap/
•	Prof. Dr. Stefan Hockertz zu den sogenannten Impfstoffen und deren Test und Entwicklung - bereits vom 07.07.2020
https://www.bitchute.com/video/zP8T0Ol1Zw2B/
https://tinyurl.com/7u89mfus
•	Geert Vanden Bossche (DVM and PhD) und Peter McCullouch (MD, MPH) zur sogenannten Corona-Impfung - vom 15.03.2021
https://www.youtube.com/watch?v=2LSMpuQcTSE
•	Dr. Josef Thoma - Impfung Sinnvoll oder nicht?
https://www.youtube.com/watch?v=LuOu9y-Ilpk
•	Ärzte für Aufklärung RA Dr. jur. Brunner zur mRNA-Gentherapie, die als Impfung ausgegeben wird.
https://www.bitchute.com/video/RmwZTCV2jXsd/

•	In der renommierten Fachzeitschrift „The Lancet“ ist bereits am 20.04.2021 folgendes zu den Corona-Impfstoffen veröffentlich worden:

Die Schutzrate beläuft sich gem. der Studienergebnisse auf:
1,3% bei AstraZeneca-Oxford
1,2% bei Moderna-NIH
1,2% bei Johnson&Johnson
0,93% bei Gamaleya und
0,84% bei Pfizer/BioNTech
Ärzte für Aufklärung und Link zur Originalpublikation
https://www.aerztefueraufklaerung.de/news/index.php
https://tinyurl.com/y5z6v8ce
Link zum Originalartikel - The Lancet
https://www.thelancet.com/journals/lanmic/article/PIIS2666-5247(21)00069-0/fulltext
https://tinyurl.com/xtsvu7ym
•	Corona Schutzimpfung - eine aktuelle Bilanz
http://info-medico.de/index.php/impfungen-erste-bilanz
•	Liste mit Impfnebenwirkungen - Regierung UK
https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/994380/COVID-19_mRNA_Pfizer_BioNTech_Vaccine_Analysis_Print_9.06.2021.pdf
https://tinyurl.com/rrnk5j76
•	WHO-Datenbank: Mehr als 1,6 Millionen gemeldete Nebenwirkungen, 10.554 Tote
https://sciencefiles.org/2021/08/04/who-datenbank-mehr-als-16-millionen-gemeldete-nebenwirkungen-10-554-tote-uberproportional-viele-herzerkrankungen-nach-covid-impfung
•	The Safety of COVID-19 Vaccinations (4 sterben um 2-11 zu retten pro 100.000)
https://www.mdpi.com/2076-393X/9/7/693/pdf
https://www.mdpi.com/2076-393X/9/7/693/htm
Diese Studie wurde, vermutlich wegen dem Druck i.V.m. dem provokanten Titel zurückgenommen, die Zahlen die ausgewertet wurden sind aber selbstverständlich weiterhin offiziell valide.
•	Studie des National Center for Biotechnology Information wiederlegt, eine nennenswerte Wirksamkeit der sog. Corona-Impfstoffe.
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8481107

•	Bereits am 30 Augst hatte Steve Kirsch auf der Seite des CDC über eine schockierende Zahl von Todesfällen und Impfschäden
https://www.regulations.gov/comment/CDC-2021-0089-0024

Attachment1 Kirsch ACIP -> https://downloads.regulations.gov/CDC-2021-0089-0024/attachment_3.pdf
Attachment2 Kirsch ACIP Vaccine deaths -> https://downloads.regulations.gov/CDC-2021-0089-0024/attachment_1.pdf
Attachment3 Kirsch ACIP Guetzkow -> https://downloads.regulations.gov/CDC-2021-0089-0024/attachment_2.pdf

•	Studie von Prof. Dr. Rolf Steyer und Dr. Gregor Kappler der Uni Jena zur Übersterblichkeit: „Je höher die Impfquote, desto höher die Übersterblichkeit“
https://www.rundschau.info/studie-zur-uebersterblichkeit-je-hoeher-die-impfquote-desto-hoeher-die-uebersterblichkeit/
https://tinyurl.com/8xtdzhnb

•	Neue Studie aus der Schweiz belegt erneut, dass die sog. Impfstoffe wertlos und unsicher sind.
https://odysee.com/@Impfsch%C3%A4den:a/202111242230:6
Webseite zu Veranstaltung
https://aletheia-scimed.ch/ALETHEIA-Medienkonferenz-vom-Freitag-12-November-2021
PDF zur Veranstaltung
https://aletheia-scimed.ch/IMG/pdf/prasentation_medienkonfernz_12.11.21.pdf


Impfdurchbrüche
•	RKI überführt sich selbst - wurden die Zahlen absichtlich fehlinterpretiert?
https://odysee.com/@Impfsch%C3%A4den:a/202110032245:7

•	 Prof. Dr. Werner Bergholz – Eine Zusammenfassung der letzten 19 Monate...
https://odysee.com/@Impfsch%C3%A4den:a/202110041548:8

•	Impf-Nebenwirkungen melden und die Datenbank von Paul-Ehrlich-Institut
https://www.pei.de/DE/arzneimittelsicherheit/pharmakovigilanz/meldeformulare-online-meldung/nebenwirkungsmeldung-verbraucher-inhalt.html

•	RKI überführt sich in seinen Wochenberichten selbst - Die bisherigen Zahlen zu den Impfdurchbrüchen sind falsch.
https://odysee.com/@Impfsch%C3%A4den:a/202110032245:7


Pandemie Planspiele des WWF
•	Projekt 201 des Welt-Wirtschafts-Forums von Herbst 2019
https://www.rubikon.news/artikel/geplante-wirklichkeit

•	Ein geleaktes Strategiepapier des Bundesministeriums des Inneren belegt das die Panikmache Vorsatz war und die Regierung von der Nutzlosigkeit und schädigenden Wirkung der Maßnahmen vorab also 03/2020 wusste.
https://odysee.com/@Impfsch%C3%A4den:a/202005072015:0

•	Das geleakte Strategiepapier des BMI incl. Erklärung der Wissenschaftler und Experten hierzu.
https://trello.com/1/cards/615c8985be3c731a2c213019/attachments/615c8a8479da9d229a3f3fc1/download/20200315_-_Anfrage_zu_BMI-Strategiepapier-incl._der_wissenschaftlichen_Autoren.pdf
•
Pressemitteilung der Experten des Corona-Papiers aus dem Bundesministerium des Innern
https://www.abendzeitung-muenchen.de/media.media.98cfe8dc-2b67-4861-899d-d12b7f65fbe4.original.pdf


Die fragwürdigen „Experten“
•	Die Akte Wieler: Verflechtungen und Enthüllungen
https://odysee.com/@Deutsche-Mitte:7/DieAkteWielerVerflechtungenUnd_360p:e
https://tinyurl.com/83ubc9pa
•	Die Akte Karl Lauterbach: Dringende Warnung vor dem Warner!
https://odysee.com/@Deutsche-Mitte:7/202107271434:0
https://tinyurl.com/epu6r5bd
•	Die Akte Christian Drosten: Fragwürdiger akademischer Hintergrund
https://odysee.com/@Deutsche-Mitte:7/202107271442:6
https://tinyurl.com/4hn3wrnc

Inszenierte Pandemie
•	Dokumentation zum ersten großen Fehlalarm 2008/2009 von und mit Herrn Drosten.
https://www.bitchute.com/video/rnToOxQNzmF0/
•	Inzidenzwerte des RKI
https://www.youtube.com/watch?v=m-KZnEfj5X8&list=WL&index=3
•	Prof. Dr. Sucharit Bhakdi erklärt die Wirkung der neuartigen mRNA-Corona-Impfungen im Körper der Geimpften.
https://odysee.com/@Deutsche-Mitte:7/202108041027:d

•	Sehr gute Leseprobe aus dem Buch von Prof. Dr. Bhakdi

zu Impfungen und Immunität... Studien aus USA und Schweden belegen eindeutig, das 80% bereits Immun sind.
Der angebliche Virus kann daher kein neuer Virus sein… (Hinweis auf Seite 11) vom 29.09.2020
https://coronafehlalarm.de/wp-content/uploads/2021/02/corona-fehlalarm_anhang-immunitaet_2020-09-29.pdf
https://tinyurl.com/m9u87aa2
zu Zahlen, Daten und Hintergründen...
https://coronafehlalarm.de/wp-content/uploads/2021/02/corona_unmasked_leseprobe.pdf
https://tinyurl.com/buj2k4ew
•	Dr. David Bauer: Pfizer-Impfstoff verhindert die Bildung von wichtigen Antikörper
Das Immunsystem von Geimpften ist 5-6 mal anfälliger…
https://www.legitim.ch/post/newsbombe-neue-cdc-studie-best%C3%A4tigt-74-der-neuen-corona-f%C3%A4lle-sind-voll-geimpft
Die Studie dazu
https://www.cdc.gov/mmwr/volumes/70/wr/mm7031e2.htm?s_cid=mm7031e2_w#F2_down
https://odysee.com/@Deutsche-Mitte:7/202108011434:c

Impfschäden durch die mRNA-Gentherapie
•	Einige Videos zu den Impfschäden
https://odysee.com/@Impfsch%C3%A4den:a

•	Dr. Josef Thoma erklärt wie man das für und wider, bezüglich einer Impfung abwägt.
https://odysee.com/@Impfsch%C3%A4den:a/202104281425:7

•	Pathologen enthüllen Obduktionsergebnisse von verstorbenen Corona-Geimpften vom 21.09.2021
https://odysee.com/@Impfsch%C3%A4den:a/202109221518:d

•	Experten Hearing im US-Senat zu den exorbitanten Impfschäden durch die „Corona-Impfstoffe“
https://tkp.at/2021/11/08/fehlende-daten-zur-impfstoffsicherheit-experten-hearing-im-us-senat/
https://tinyurl.com/57vkvn35

•	Schaubilder auf Basis von Rohdaten zu Nebenwirkungen der „Corona-Impfungen“
Anleitung: https://www.youtube.com/watch?v=4HpUYEGCKtM

o	Übersicht Schaubilder 	-> https://langesexcel.de/die-onepager.html
o	Der jeweils aktuelle Report 	-> https://www.impfnebenwirkungen.net/report.pdf
o	Das jeweils aktuelle Schaubild 	-> https://www.impfnebenwirkungen.net/onepager.pdf
o	Tabellen 			->  https://impfnebenwirkungen.net/ema/tabellen

•	Prof. Peter Schirmacher, Chef-Pathologe der Uni Heidelberg fordert mehr Obduktionen - vom 01.08.2021
30-40 Prozent der bisher Obduzierten sind ursächlich an der Impfung gestorben.
https://www.transparenztest.de/post/chefpathologe-uni-heidelberg-30-40-prozent-ursaechlich-an-covid-impfung-verstorben
https://tinyurl.com/crehynbm

Beitrag zu den Meldedaten des Vaers-System CDC USA - Es gibt verheerende Nebenwirkungen durch die mRNA-Gentherapie (Corona-Impfung) außerdem der „Statistikbetrug“ des Paul-Ehrlich-Instituts... vom 05.11.2021 mit Stand vom 30.08.2021
https://odysee.com/@Impfsch%C3%A4den:a/202111042150:f

•	Rote-Hand-Brief:

Der Rote-Hand-Brief ist eine in Deutschland gebräuchliche Form eines Informationsschreibens, mit dem pharmazeutische Unternehmen heilberufliche Fachkreise über neu erkannte Arzneimittelrisiken informieren…

o	BioNTech und Moderna zu den Impfstoffen Comirnaty und Spikevax
https://www.pei.de/SharedDocs/Downloads/DE/newsroom/veroeffentlichungen-arzneimittel/rhb/21-07-19-covid-19-comirnaty-und-spikevax.pdf?__blob=publicationFile&v=5
https://tinyurl.com/2pewzdws
o	Johnson&Johnson
https://www.akdae.de/Arzneimittelsicherheit/RHB/20210426.pdf
https://tinyurl.com/77pvpdhj
o	AstraZeneca
https://www.akdae.de/Arzneimittelsicherheit/RHB/20210413.pdf
https://tinyurl.com/rcrk42ry


Auswertung der Rohdaten zu Corona
•	Die „Pandemie“ in den Rohdaten von Marcel Barz...
https://odysee.com/@Deutsche-Mitte:7/202108311415:3

•	80 % der sogenannten Corona-Toten sind nicht an Corona gestorben
https://www.24vita.de/verbraucher/corona-covid-tote-todesursache-sterbefaelle-rki-iges-hauessler-mediziner-berlin-90952534.html

•	Universität Duisburg / Essen analysiert Sterbegeschehen - Ergebnis 2020 gab es Keine erhöhte Sterberate durch COVID-19
https://www.uni-due.de/2021-10-21-keine-uebersterblichkeit-durch-corona


Gerede von einer Impfflicht
•	In welchem licht jemand steht, der glaubt die körperliche Unversehrtheit anderer Menschen missachten zu können, kann man gut beim RKI nachlesen.

Stellungnahme von Prof. Dr. Dr. h.c. mult. Jörg Hacker, Präsident des Robert Koch-Instituts.
https://www.rki.de/DE/Content/Service/Presse/Pressetermine/presse_rki_ns_Stellungnahme.html

Wer glaubt die körperliche Unversehrtheit anderer missachten zu können, muss sich nicht wundern, wenn diese Anderen irgendwann dessen körperliche Unversehrtheit nicht mehr achten werden…


Zurückrudern
•	Oberstes Gesundheitsinstitut Italiens korrigiert die geschätzten Covid-Todesfälle von über 130’000 auf unter 4000 herunter
https://corona-transition.org/oberstes-gesundheitsinstitut-italiens-korrigiert-die-geschatzten-covid

Artikel von Dailysceptic
https://dailysceptic.org/2021/11/03/italian-higher-institute-of-health-adjusts-number-of-deaths-due-to-covid-alone-since-february-2020-downwards-from-over-130000-to-under-4000/
Artikel IL Tempo
https://www.iltempo.it/attualita/2021/10/21/news/rapporto-iss-morti-covid-malattie-patologie-come-influenza-pandemia-disastro-mortalita-bechis-29134543/

Netzwerke der NWO
•	Darstellung der Netzwerke, die diese "Pandemie" erschaffen haben
https://odysee.com/@Neue-Welt-Ordnung:0/202109251215:9
Interviewe mit dem Datenanalysten
https://odysee.com/@Neue-Welt-Ordnung:0/202109221548:e
Das Dokument das die Netzwerke darstellt
https://clubderklarenworte.de/wp-content/uploads/2021/09/Netzwerkanalyse-Corona-Komplex.pdf

•	Ein Beispiel aus dem Netzwerk im Detail erklärt
https://odysee.com/@Neue-Welt-Ordnung:0/202109281458:3


•	Goldman Sachs - Das Organigramm der Korruption
https://odysee.com/@Neue-Welt-Ordnung:0/202010282115:d

•	Bargeldabschaffung: Die Versklavung durch die Digitale Währung
https://odysee.com/@Neue-Welt-Ordnung:0/202109221447:9


Virus und tatsächliche Gefahr
•	Stanford-Professor Ioannidis wertet 61 Studien zur Gefahr des Virus aus – bereits v. 09/2020
https://www.merkur.de/welt/who-corona-studie-tote-uebersterblichkeit-infektion-pandemie-zr-90073439.html
https://tinyurl.com/249w3yh6
•	Veröffentlichung der WHO hierzu – Covid 19 ist weniger gefährlich als eine Grippe
https://www.who.int/bulletin/online_first/BLT.20.265892.pdf
https://tinyurl.com/ktz3mz6p
•	Mortalität der Influenza (Grippe) zum Vergleich mit „Corona“
https://www.rki.de/DE/Content/Infekt/EpidBull/Archiv/2015/Ausgaben/03_15.pdf?__blob=publicationFile
https://tinyurl.com/4ape47x7

•	Internationale Experten verneinen eine bestehende Gefahr
https://www.bitchute.com/video/S7tCXuhCahbJ/

•	Deutsche Wissenschaftler wiedersprechen endlich
https://www.wissenschaftstehtauf.de/

•	Prof. Klaus Püschel nach Obduktion sog. Corona-Toter „In Hamburg ist niemand ohne Vorerkrankung an Corona gestorben“
https://www.welt.de/regionales/hamburg/article207086675/Rechtsmediziner-Pueschel-In-Hamburg-ist-niemand-ohne-Vorerkrankung-an-Corona-gestorben.html
https://tinyurl.com/2kav5vxt

•	Dr. Derek Knauss und seine Kollegen haben in 1.500 „corona-positiv“ getesteten Menschen kein Covid-19 finden, nur Influenza A und B - Das Virus Covid-19 gibt es nicht -
https://journalistenwatch.com/2021/09/12/das-virus-covid/

•	Interessant auch, wenn man sich überlegt, dass nach Aussage des CDC USA niemals ein Virus isoliert wurde - Stand 21.07.2021.
Herr Drosten hat lediglich eine digitale und theoretische Abstraktion auf einem Computer erstellt, die auf einer gnomischen Datenbank basiert und der lediglich 4 der üblichen 10 Gene definiert um den Virus im Model glaubhaft zu machen.

https://odysee.com/@Impfsch%C3%A4den:a/202111071548:5


Das inszenierte Theater der Medien
•	Ein Beitrag, der einmal mehr zeigt, wie das Theater inszeniert wird.
https://www.youtube.com/watch?v=AUtim48Lfh0

Lügen der „Leitmedien“
•	Die Auftragslügner vom Spiegel - wes Brot ich es, des Lied ich sing - Bill Gates bezahlt…
https://www.bitchute.com/video/K2Lt5Li82aN0/

Gates-Stiftung unterstützt den Spiegel mit weiteren 2,9 Millionen Dollar - Könnte die willfährige Berichterstattung evtl. der Grund hierfür sein?
•	https://www.berliner-zeitung.de/news/gates-stiftung-unterstuetzt-den-spiegel-mit-weiteren-29-millionen-dollar-li.194183

•	Staatsfunk DDR und BRD - wo ist der Unterschied
https://odysee.com/@L%C3%BCgenpresse:3/202109062019:3

•	So werden Menschen vom SWR2 diffamiert - offenbar kann es mittlerweile jeden treffen...
https://www.youtube.com/watch?v=AvZz-hRu5sk

Links zu guten Blogs
•	Corona Transition
https://corona-transition.org/?rubrique=11&parent=11

•	Peter F. Mayer bloggt
https://tkp.at/

•	Webseite Dr. Wolfgang Wodarg
https://www.wodarg.com

•	Swiss
https://swprs.org/fakten-zu-covid-19

Inszenierte Pandemie von 2009
•	Profiteure der Angst (Arte-Doku 2009) – Hauptbeteiligter Herr Drosten
https://www.bitchute.com/video/YAcsJ7bscLyv/
https://tinyurl.com/9xyff4su


Die gekauften „Faktenchecker“ von Correctiv vor Gericht
•	Ein Artikel zu den „Faktencheckern“ von Correctiv.
Das OLG Karlsruhe entscheidet, dass diese Meinung und nicht Tatsachen verbreiten und verteilt 7 Ohrfeigen für die bezahlten Stimmungsmacher.
https://www.tichyseinblick.de/tichys-einblick/sieben-ohrfeigen-fuer-correctiv
https://tinyurl.com/4nfaekpf
•	Correctiv verliert erneut und stellt fest: „nicht Tatsachenbehauptungen, sondern um Wertungen und Meinungen“
https://www.tichyseinblick.de/daili-es-sentials/correctiv-erneute-niederlage-vor-gericht/
https://tinyurl.com/64thtj2j
OLG Karlsruhe, 27.05.2020 - AZ 6U36/20
http://lrbw.juris.de/cgi-bin/laender_rechtsprechung/document.py?Gericht=bw&sid=e44bc88cd5beb4343e45bff5f47fee3d&nr=31404&pos=0&anz=1
https://tinyurl.com/u6h9dsdy
•	Die Finanzen der bestellten „Faktenchecker“
https://www.steinhoefel.com/2020/06/faktencheck-bei-den-faktencheckern-folge-2-die-finanzen.html
Wundern sie sich nicht warum es so etwas wie diese Meinungsverstärker gibt?
Und warum diese bei Google immer an erster Stelle stehen, wenn Sie zu ganz bestimmten Themen bei Google suchen?
•	Wer löscht und zensiert in Deutschland obwohl es ja nach Art. 5 GG keine Zensur gibt?
https://www.youtube.com/watch?v=fSBbPyS-Kag

•	Amadeu-Stiftung
https://vimeo.com/229755791

Wie Wikipedia zur Denunzierung Missbraucht wird
•	Wie das denunzieren redlicher Wissenschaftler in der Wikipedia abläuft kann man hier nachlesen.
Das Ganze ist durch das LG Hamburg und das OLG Hamburg in Verfahren bestätigt.
https://de.linkedin.com/pulse/wikipedia-verliert-vor-gericht-und-denunziert-weiter-bernd-henke
https://tinyurl.com/tz49nba8

•	Gericht bestätig auch in zweiter Instanz die Manipulation bei  Wikipedia
https://www.youtube.com/watch?v=XIvW9piQS80&t=536s

•	So funktioniert die Manipulation
https://www.youtube.com/watch?v=O2pFqJvsVy0
•	Beitrag mit Dr. Daniele Ganser (wurde im o.g. Wiki-Beitrag benannt)
https://www.youtube.com/watch?v=q2i7eMqrjF8

•	Artikel von Paul Schreyer (wurde im o.g. Wiki-Beitrag benannt)
https://kenfm.de/es-geht-nicht-um-gesundheitsschutz-von-paul-schreyer/

•	Psiram die anonyme Plattform zur Denunzierung redlicher Wissenschaftler und Jornalisten. https://www.berlinertageszeitung.de/technik/30006-psiram-webseite-krimineller-macher-ohne-impressum-aber-mit-wikipedia-eintrtag.html

https://tinyurl.com/nz3ep2ut


Wozu könnte dass alles dienen?
•	Einführung eines Sozialkreditsystems zur Kontrolle und Überwachung
https://www.youtube.com/watch?v=1PJpQS2bO3k
•	Beitrag zum Projekt KTDI des WWF (leider nur noch als mp3, da Youtube selbst oder im Auftrag zensiert)
https://kenfm.de/standpunkte-%e2%80%a2-die-totalitaere-horrorvision-des-weltwirtschaftsforums-wird-wahr-gemacht/
•	Projektseite des WWF mit Whitepaper (als Nachweis)
https://www.weforum.org/whitepapers/known-traveller-digital-identity-specifications-guidance

•	Schweden: Mikrochips unter der Haut sollen das Leben der Menschen erleichtern
https://www.youtube.com/watch?v=Zrpq5i0ErtE

•	Tui implantiert Mikrochips in Mitarbeiter-Hände (der neue Ausweis/Impfpass)
https://www.spiegel.de/karriere/schweden-tui-mitarbeiter-tragen-mikrochips-unter-der-haut-a-1287060.html

•	So werden unsere Kinder vom ARD Kinderkanal schon mal auf den RFID-Chip vorbereitet
https://www.bitchute.com/video/IlQLj4HB18y8/

•	Der Staatsfunk will uns den RFID Chip und die Bargeldabschaffung schmackhaft machen
https://odysee.com/@Neue-Welt-Ordnung:0/202109171948:4
•	Der erste Corona-Chip ist erkennbar - wie vor zwei Jahren gesagt geht es nicht um Gesundheit sondern um Kontrolle.
https://pubmed.ncbi.nlm.nih.gov/15349945

•	Nicolaus Fest (AFD) fasst die Corona-Lügen der Altparteien und ihrer Propagandisten der Leitmedien zusammen.
https://odysee.com/@Impfsch%C3%A4den:a/202111292017:4

•	England strebt Quartalsweise Impfpflicht an - eine Verrschwörungtheorie wird erneut wahr.
https://odysee.com/@Impfsch%C3%A4den:a/202111302114:e


Ein paar gute Kanäle zu...
•	Aktuellen Themen
https://odysee.com/@Deutsche-Mitte:7

•	Lügenpresse
https://odysee.com/@L%C3%BCgenpresse:3

•	Corona-Impfschäden
https://odysee.com/@Impfsch%C3%A4den:a

•	Neue-Welt-Ordnung
https://odysee.com/@Neue-Welt-Ordnung:0

•	Klima- und Co2-Lüge
https://odysee.com/@Klimal%C3%BCge:9

•	Ereignissen auf Demos
https://odysee.com/@Demobilder:6

•	Indoktriniert und verblödet
https://odysee.com/@Indoktriniert-und-verbl%C3%B6det:3

•	Gewalttaten in unserem Land
https://odysee.com/@Gewalttaten:d


Unzensiere Nachrichten:
•	News zu Corona

o	https://corona-ausschuss.de

o	https://www.aerztefueraufklaerung.de

o	https://www.afaev.de

o	https://www.individuelle-impfentscheidung.de

•	News Allgemein

o	https://apolut.net

o	https://www.rubikon.news

o	https://www.tichyseinblick.de

o	https://reitschuster.de

o	https://politik.der-privatinvestor.de

PPSD? Experten" sagen, dass 300.000 Briten aufgrund einer neuen Krankheit namens "Post-Pandemic Stress Disorder" ein Risiko für Herzprobleme haben

Zwei Londoner Ärzte haben davor gewarnt, dass mehr als eine Viertelmillion Briten von einer neuen Herzerkrankung infolge der "Post-Pandemie-Stress-Störung" (PPSD) betroffen sein könnten. Ihrer Ansicht nach könnte dies zu einem Anstieg der Herz-Kreislauf-Erkrankungen in Großbritannien um 4,5 % führen, wobei die 30- bis 45-Jährigen am meisten gefährdet sind.

Die Behauptungen der Ärzte kommen weniger als einen Monat nach einem Bericht von Dr. Steven Gundry in der American Heart Association, in dem er sagte, dass mRNA-COVID-Impfstoffe das Risiko für die Entwicklung eines akuten Koronarsyndroms, wie z. B. eines Herzinfarkts, mehr als verdoppeln.

♟Abonniere und teile den Kanal ♟



Impfschäden im Vears-System der CDC – das US-Fernsehen berichtet mittlerweile
https://odysee.com/@Impfsch%C3%A4den:a/202111122017:4
Eine Anhörung im US-Senat zu den enormen Impfschäden ist weiter unten mit dabei.


Virusgefahr

Stanford-Professor Ioannidis wertet 61 Studien zur Gefahr des Virus aus – bereits v. 09/2020
https://www.merkur.de/welt/who-corona-studie-tote-uebersterblichkeit-infektion-pandemie-zr-90073439.html

Veröffentlichung der WHO hierzu – Covid 19 ist weniger gefährlich als eine Grippe
https://www.who.int/bulletin/online_first/BLT.20.265892.pdf

Zahlen des RKI zur Mortalität der Influenza (Grippe) zum Vergleich
https://www.rki.de/DE/Content/Infekt/EpidBull/Archiv/2015/Ausgaben/03_15.pdf?__blob=publicationFile


-------------------------------------------------

Übersterblichkeit

Universität Duisburg / Essen analysiert Sterbegeschehen - Ergebnis 2020 gab es Keine erhöhte Sterberate durch COVID-19
https://www.uni-due.de/2021-10-21-keine-uebersterblichkeit-durch-corona

Die „Pandemie“ in den Rohdaten von Marcel Barz...
https://odysee.com/@Deutsche-Mitte:7/202108311415:3

07.04.2020 – Rechtsmediziner Prof. Klaus Pueschel „In Hamburg ist niemand ohne Vorerkrankung an Corona gestorben“
https://www.welt.de/regionales/hamburg/article207086675/Rechtsmediziner-Pueschel-In-Hamburg-ist-niemand-ohne-Vorerkrankung-an-Corona-gestorben.html

-------------------------------------------------

PCR-Test

Universität Duisburg und Essen weisen im renommierten Journal of Infection darauf hin, dass der PCR-Test nicht aussagefähig ist. Bis zu 78 % der Tests sind falsch positiv.
https://www.uni-due.de/2021-06-18-studie-aussagekraft-von-pcr-tests

Beitrag im renommierten Journal of Infection
https://www.journalofinfection.com/article/S0163-4453(21)00265-6/fulltext

Ärzteblatt v. 12.06.2020 zur Belastbarkeit des PCR-Test des Herren Drosten
https://www.aerzteblatt.de/archiv/214370/PCR-Tests-auf-SARS-CoV-2-Ergebnisse-richtig-interpretieren

-------------------------------------------------

Corona-Impfungen (mRNA-Gentherapie)

In der renommierten Fachzeitschrift „The Lancet“ ist am 20.04.2021 folgendes zu den "Corona-Impfstoffen" veröffentlich worden:

Die Schutzrate beläuft sich gem. der Studienergebnisse auf:
1,3% bei AstraZeneca-Oxford
1,2% bei Moderna-NIH
1,2% bei Johnson&Johnson
0,93% bei Gamaleya und
0,84% bei Pfizer/BioNTech

Link zum Originalartikel - The Lancet
https://www.thelancet.com/journals/lanmic/article/PIIS2666-5247(21)00069-0/fulltext


Studie des National Center for Biotechnology Information wiederlegt, eine nennenswerte Wirksamkeit der sog. Corona-Impfstoffe.
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8481107


-------------------------------------------------

Impfschäden

Experten Hearing im US-Senat zu Impfschäden und fehlenden Daten bezüglich der Impfstoffsicherheit
https://tkp.at/2021/11/08/fehlende-daten-zur-impfstoffsicherheit-experten-hearing-im-us-senat/

Es zeigt sich nun, dass genau die Nebenwirkungen erkennbar werden, auf die Prof. Bhakdi vor einem Jahr hingewiesen hat.
In seinem Buch beschreibt er ausführlich wie das Immensestem reagiert und das 70-80 % bereits immun gegen das angeblich neue Virus sind.
https://coronafehlalarm.de/wp-content/uploads/2021/02/corona-fehlalarm_anhang-immunitaet_2020-09-29.pdf

Zu beachten ist, dass Herr Drosten lediglich eine digitale und theoretische Abstraktion auf einem Computer erstellt, die auf einer gnomischen Datenbank basiert und bei der meines Wissens lediglich 4 von 10 „Gene“ definiert wurden um den Virus im Model glaubhaft zu machen. Auch nach Ansicht des CDC wurde der Virus hierdurch nicht eindeutig Isoliert und nachgewiesen.
https://odysee.com/@weiszpflog:5/Virus-nicht-isoliert:d


WHO-Datenbank: Mehr als 1,6 Millionen gemeldete Nebenwirkungen, 10.554 Tote
https://sciencefiles.org/2021/08/04/who-datenbank-mehr-als-16-millionen-gemeldete-nebenwirkungen-10-554-tote-uberproportional-viele-herzerkrankungen-nach-covid-impfung


Schaubilder auf Basis von Rohdaten zu Nebenwirkungen der „Corona-Impfungen“
Anleitung: https://www.youtube.com/watch?v=4HpUYEGCKtM

Übersicht Schaubilder                  -> https://langesexcel.de/die-onepager.html

Der jeweils aktuelle Report        -> https://www.impfnebenwirkungen.net/report.pdf

Das jeweils aktuelle Schaubild -> https://www.impfnebenwirkungen.net/onepager.pdf

Tabellen                                             ->  https://impfnebenwirkungen.net/ema/tabellen


Prof. Peter Schirmacher, Chef-Pathologe der Uni Heidelberg fordert mehr Obduktionen.
30-40 Prozent der bisher Obduzierten sind ursächlich an der Impfung gestorben.
https://www.transparenztest.de/post/chefpathologe-uni-heidelberg-30-40-prozent-ursaechlich-an-covid-impfung-verstorben


RKI überführt sich selbst - wurden die Zahlen absichtlich fehlinterpretiert?
https://odysee.com/@Impfsch%C3%A4den:a/202110032245:7


Rote-Hand-Brief:

Der Rote-Hand-Brief ist eine in Deutschland gebräuchliche Form eines Informationsschreibens, mit dem pharmazeutische Unternehmen heilberufliche Fachkreise über neu erkannte Arzneimittelrisiken informieren…

BioNTech und Moderna zu den Impfstoffen Comirnaty und Spikevax
https://www.pei.de/SharedDocs/Downloads/DE/newsroom/veroeffentlichungen-arzneimittel/rhb/21-07-19-covid-19-comirnaty-und-spikevax.pdf?__blob=publicationFile&v=5

Johnson&Johnson
https://www.akdae.de/Arzneimittelsicherheit/RHB/20210426.pdf

AstraZeneca
https://www.akdae.de/Arzneimittelsicherheit/RHB/20210413.pdf


-------------------------------------------------

Der Staatsrechtler Professor Dr. Dietrich Murswiek bestätigt mit seinem Rechtsgutachten die Verfassungswidrigkeit des indirekten COVID-19-Impfzwangs

Zusammenfassung
https://impfentscheidung.online/wp-content/uploads/2021/10/Kurzzusammenfassung-Gutachten.pdf

Gesamtes Rechtsgutachten
https://impfentscheidung.online/wp-content/uploads/2021/10/Gutachten-Die-Verfassungswidrigkeit-des-indirekten-Corona-Impfzwangs.pdf

Interview
https://odysee.com/@Deutsche-Mitte:7/202110092114:d


Dr. Pieter Schleiter ist Richter und äußert sich zur aktuellen Situation unseres Rechtsstaats
https://odysee.com/@Deutsche-Mitte:7/202110032205:6



Der Verwaltungsgerichtshof Bayern hat die Ausgangsperre von März 2021 (BayMBl. 2020 Nr. 162) für unwirksam und damit rechtswidrig erklärt.
VGH München, Beschluss v. 04.10.2021 – 20 N 20.767
https://www.gesetze-bayern.de/Content/Document/Y-300-Z-BECKRS-B-2021-N-29086


-------------------------------------------------

Wozu möchte Spahn die Landes-Parlamente auch weiterhin umgehen?

Das Infektionsschutzgesetz gibt den Ländern in Paragraf 28a ausdrücklich die Möglichkeit, nach dem Ende einer „epidemischen Lage“, Corona-Maßnahmen weiter anzuwenden, sofern der jeweilige Landtag dies beschließt. Auf dieses Vorgehen hat auch Spahn die Koalitionäre in einem Brief hingewiesen. Zudem hat er eine Alternative skizziert. Demnach könnte Paragraf 28a des Infektionsschutzgesetzes vom Bundestag so geändert werden, dass die Corona-Maßnahmen, die von den Landesregierungen bislang per Verordnung erlassen werden können, nicht mehr an das Bestehen einer bundesweiten „epidemischen Lage“ geknüpft werden.
Damit könnten die Landesregierungen ihre Corona-Verordnungen fortschreiben, ohne dass sie einen Landtagbeschluss benötigen.

https://www.faz.net/aktuell/politik/inland/corona-massnahmen-was-nach-ende-der-epidemischen-lage-passiert-17595244.html


Gesicherte Videos bei Odysee…

-> Aktuelle Themen - https://odysee.com/@Deutsche-Mitte:7

-> Lügenpresse - https://odysee.com/@L%C3%BCgenpresse:3

-> Corona-Impfschäden - https://odysee.com/@Impfsch%C3%A4den:a

-> Neue-Welt-Ordnung https://odysee.com/@Neue-Welt-Ordnung:0

-> Klima- und Co2-Lüge - https://odysee.com/@Klimal%C3%BCge:9

-> Ereignisse auf Demos - https://odysee.com/@Demobilder:6

-> Indoktriniert und verblödet - https://odysee.com/@Indoktriniert-und-verbl%C3%B6det:3

-> Gewalttaten in unserem Land - https://odysee.com/@Gewalttaten:d



